//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoursApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int nTypeConnect {
            get {
                return ((int)(this["nTypeConnect"]));
            }
            set {
                this["nTypeConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Полезная модель")]
        public string cAppName {
            get {
                return ((string)(this["cAppName"]));
            }
            set {
                this["cAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Нет")]
        public string cExtension {
            get {
                return ((string)(this["cExtension"]));
            }
            set {
                this["cExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int nStyleKod {
            get {
                return ((int)(this["nStyleKod"]));
            }
            set {
                this["nStyleKod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin")]
        public string cUser {
            get {
                return ((string)(this["cUser"]));
            }
            set {
                this["cUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cRole {
            get {
                return ((string)(this["cRole"]));
            }
            set {
                this["cRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int nRoleId {
            get {
                return ((int)(this["nRoleId"]));
            }
            set {
                this["nRoleId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int nTypeLogin {
            get {
                return ((int)(this["nTypeLogin"]));
            }
            set {
                this["nTypeLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int nUserId {
            get {
                return ((int)(this["nUserId"]));
            }
            set {
                this["nUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte nSetupLogin {
            get {
                return ((byte)(this["nSetupLogin"]));
            }
            set {
                this["nSetupLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flConfidential {
            get {
                return ((bool)(this["flConfidential"]));
            }
            set {
                this["flConfidential"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flEnabledSynch {
            get {
                return ((bool)(this["flEnabledSynch"]));
            }
            set {
                this["flEnabledSynch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flStyleSynch {
            get {
                return ((bool)(this["flStyleSynch"]));
            }
            set {
                this["flStyleSynch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flModelsSynch {
            get {
                return ((bool)(this["flModelsSynch"]));
            }
            set {
                this["flModelsSynch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flOtherSynch {
            get {
                return ((bool)(this["flOtherSynch"]));
            }
            set {
                this["flOtherSynch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UUID {
            get {
                return ((string)(this["UUID"]));
            }
            set {
                this["UUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flEnabledStyle {
            get {
                return ((bool)(this["flEnabledStyle"]));
            }
            set {
                this["flEnabledStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flStyleInTop {
            get {
                return ((bool)(this["flStyleInTop"]));
            }
            set {
                this["flStyleInTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flDateInBottom {
            get {
                return ((bool)(this["flDateInBottom"]));
            }
            set {
                this["flDateInBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flKeyInBottom {
            get {
                return ((bool)(this["flKeyInBottom"]));
            }
            set {
                this["flKeyInBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int nAccountId {
            get {
                return ((int)(this["nAccountId"]));
            }
            set {
                this["nAccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::EcoursXLib.HumanFlag Flags {
            get {
                return ((global::EcoursXLib.HumanFlag)(this["Flags"]));
            }
            set {
                this["Flags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SQLDB\\EDOC")]
        public string DataRootDir {
            get {
                return ((string)(this["DataRootDir"]));
            }
            set {
                this["DataRootDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flChatAndTasks {
            get {
                return ((bool)(this["flChatAndTasks"]));
            }
            set {
                this["flChatAndTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 32, 32")]
        public global::System.Drawing.Color ChatWallPaper {
            get {
                return ((global::System.Drawing.Color)(this["ChatWallPaper"]));
            }
            set {
                this["ChatWallPaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatPathImg {
            get {
                return ((string)(this["ChatPathImg"]));
            }
            set {
                this["ChatPathImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatPathDoc {
            get {
                return ((string)(this["ChatPathDoc"]));
            }
            set {
                this["ChatPathDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::EcoursXLib.PartnerFlag PFlags {
            get {
                return ((global::EcoursXLib.PartnerFlag)(this["PFlags"]));
            }
            set {
                this["PFlags"] = value;
            }
        }
    }
}
